### PR TITLE
Fix EU pricing

### LINKED ISSUE #365: No instance types returned for any Europe regions on AWS
**Describe the bug**
All European regions on AWS now return no instance types - see log message `numberOfVms: 0`:

```
{"application":"cloudinfo","environment":"production","level":"debug","msg":"getting available instance types from AWS API","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","missingAttrs":{},"msg":"instance types with missing attributes","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","missingGPU":null,"msg":"instance types with missing gpu","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","msg":"couldn't find any virtual machines to recommend","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","msg":"found vms","numberOfVms":0,"provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
```

This is almost certainly caused by the [AWS SDK upgrade PR](https://github.com/banzaicloud/cloudinfo/pull/345) - noting specifically [this change in the expected region descriptions](https://github.com/banzaicloud/cloudinfo/pull/345/files#diff-b5c2ebb285b93f9707ce8481530ed2f5L180-R181) - the pricing API still uses 'EU' not 'Europe' in its location field, so this now will not match any European instances:

```
aws --region us-east-1 pricing get-attribute-values --service-code AmazonEC2 --attribute-name location --output table

----------------------------------
|       GetAttributeValues       |
+--------------------------------+
||        AttributeValues       ||
|+------------------------------+|
||             Value            ||
|+------------------------------+|
||  AWS GovCloud (US-East)      ||
||  AWS GovCloud (US-West)      ||
||  Africa (Cape Town)          ||
||  Asia Pacific (Hong Kong)    ||
||  Asia Pacific (Mumbai)       ||
||  Asia Pacific (Osaka-Local)  ||
||  Asia Pacific (Seoul)        ||
||  Asia Pacific (Singapore)    ||
||  Asia Pacific (Sydney)       ||
||  Asia Pacific (Tokyo)        ||
||  Canada (Central)            ||
||  EU (Frankfurt)              ||
||  EU (Ireland)                ||
||  EU (London)                 ||
||  EU (Milan)                  ||
||  EU (Paris)                  ||
||  EU (Stockholm)              ||
||  Middle East (Bahrain)       ||
||  South America (Sao Paulo)   ||
||  US East (N. Virginia)       ||
||  US East (Ohio)              ||
||  US West (Los Angeles)       ||
||  US West (N. California)     ||
||  US West (Oregon)            ||
|+------------------------------+|
```

**Steps to reproduce the issue:**
run cloudinfo with AWS enabled

**Additional context**
Tested on latest tagged `0.15.0`

### PR DESCRIPTION
**Pull request by sagikazarmark**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #365
| License         | Apache 2.0

### What's in this PR?
Fixes EU pricing info

### CODE REVIEW

File: internal/cloudinfo/providers/amazon/cloudinfo.go [hunk 1]
```diff
@@ -324,8 +324,16 @@ func (e *Ec2Infoer) GetRegion(id string) *endpoints.Region {
...
 // newAttributeValuesInput assembles a GetProductsInput instance for querying the provider
 func (e *Ec2Infoer) newGetProductsInput(regionId string) *pricing.GetProductsInput {
-	return &pricing.GetProductsInput{
+	region := e.GetRegion(regionId).Description()
+
+	// This is a temporary fix for the pricing API still using "EU" in the location instead of "Europe"
+	// Reported in: https://github.com/banzaicloud/cloudinfo/issues/365
+	// If the pricing API continues using "EU", we should probably find a better place for this.
+	if strings.HasPrefix(region, "Europe") {
+		region = fmt.Sprintf("EU %s", region[6:])
```
Comment (bandesz) [inline internal/cloudinfo/providers/amazon/cloudinfo.go:333]: `Europe<space>(London)` will become `EU<space><space>(London)`

Comment (sagikazarmark) [reply internal/cloudinfo/providers/amazon/cloudinfo.go:333]: Yeah, noticed during testing 🙂
